// <auto-generated />
using System;
using CoffeeShop.Products.Api.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeShop.Products.Api.Storage.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240704085732_CreateInitialMigration")]
    partial class CreateInitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoffeeShop.Products.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Coffee"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Accessories"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "FoodItems"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Others"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "WholeBean",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ground",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Instant",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pods",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Specialty",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CoffeeMakers",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Grinders",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mugs",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Filters",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pastries",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Snacks",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Syrups",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "MilkAlternatives",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Merchandise",
                            ParentCategoryId = 4
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Subscriptions",
                            ParentCategoryId = 4
                        });
                });

            modelBuilder.Entity("CoffeeShop.Products.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(727),
                            Name = "WholeBean_Product_1",
                            Price = 39.900515695959m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(770)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(778),
                            Name = "WholeBean_Product_2",
                            Price = 27.7233179468474m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(780)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(783),
                            Name = "WholeBean_Product_3",
                            Price = 21.4492731899077m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(784)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(788),
                            Name = "WholeBean_Product_4",
                            Price = 87.5436179397262m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(789)
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(792),
                            Name = "WholeBean_Product_5",
                            Price = 20.9755794449348m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(794)
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(799),
                            Name = "Ground_Product_6",
                            Price = 77.2337385251688m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(800)
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(804),
                            Name = "Ground_Product_7",
                            Price = 99.4697145783609m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(805)
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(809),
                            Name = "Ground_Product_8",
                            Price = 47.6249653452261m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(811)
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(814),
                            Name = "Ground_Product_9",
                            Price = 87.8453042904237m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(815)
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(820),
                            Name = "Ground_Product_10",
                            Price = 15.2604993210595m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(822)
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(826),
                            Name = "Instant_Product_11",
                            Price = 45.0656410259566m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(827)
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(887),
                            Name = "Instant_Product_12",
                            Price = 9.10626866750053m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(889)
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(892),
                            Name = "Instant_Product_13",
                            Price = 51.6553701825023m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(894)
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(897),
                            Name = "Instant_Product_14",
                            Price = 54.1629988663512m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(899)
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(902),
                            Name = "Instant_Product_15",
                            Price = 31.3115645095148m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(903)
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(906),
                            Name = "Instant_Product_16",
                            Price = 25.7590855880902m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(908)
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(911),
                            Name = "Instant_Product_17",
                            Price = 86.7257898597764m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(913)
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(920),
                            Name = "Instant_Product_18",
                            Price = 26.7804580804978m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(921)
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(925),
                            Name = "Pods_Product_19",
                            Price = 28.6867303756965m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(927)
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(930),
                            Name = "Pods_Product_20",
                            Price = 8.46554550753944m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(932)
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(935),
                            Name = "Pods_Product_21",
                            Price = 25.0133804200061m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(937)
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(941),
                            Name = "Pods_Product_22",
                            Price = 43.0978803926869m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(943)
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(946),
                            Name = "Pods_Product_23",
                            Price = 17.6113770298199m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(948)
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(951),
                            Name = "Pods_Product_24",
                            Price = 7.23779954710363m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(953)
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(956),
                            Name = "Pods_Product_25",
                            Price = 38.4893279548927m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(957)
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(961),
                            Name = "Pods_Product_26",
                            Price = 2.57694696862686m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(962)
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(966),
                            Name = "Specialty_Product_27",
                            Price = 84.5433456497868m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(967)
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(971),
                            Name = "Specialty_Product_28",
                            Price = 39.1717788587936m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(973)
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(976),
                            Name = "Specialty_Product_29",
                            Price = 1.96970810203454m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(978)
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(981),
                            Name = "Specialty_Product_30",
                            Price = 59.2657138030157m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(982)
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(986),
                            Name = "Specialty_Product_31",
                            Price = 90.7701928239306m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(987)
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(990),
                            Name = "Specialty_Product_32",
                            Price = 1.35810423015359m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(992)
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(995),
                            Name = "Specialty_Product_33",
                            Price = 55.2511913481889m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(996)
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1000),
                            Name = "Specialty_Product_34",
                            Price = 55.387527498995m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1002)
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1005),
                            Name = "CoffeeMakers_Product_35",
                            Price = 48.3351137939554m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1007)
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1010),
                            Name = "CoffeeMakers_Product_36",
                            Price = 83.4532813759349m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1012)
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1015),
                            Name = "CoffeeMakers_Product_37",
                            Price = 5.12909510038918m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1016)
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1019),
                            Name = "CoffeeMakers_Product_38",
                            Price = 2.35097590063488m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1021)
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1024),
                            Name = "CoffeeMakers_Product_39",
                            Price = 97.0290024969362m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1026)
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1029),
                            Name = "CoffeeMakers_Product_40",
                            Price = 0.946592644843325m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1030)
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1033),
                            Name = "CoffeeMakers_Product_41",
                            Price = 38.2958624999305m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1035)
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1038),
                            Name = "CoffeeMakers_Product_42",
                            Price = 9.95560788376686m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1040)
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1044),
                            Name = "Grinders_Product_43",
                            Price = 90.7701054071467m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1045)
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1049),
                            Name = "Grinders_Product_44",
                            Price = 83.4931190900829m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1050)
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1053),
                            Name = "Grinders_Product_45",
                            Price = 73.2967812010567m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1055)
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1058),
                            Name = "Grinders_Product_46",
                            Price = 20.5173922158827m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1059)
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1063),
                            Name = "Grinders_Product_47",
                            Price = 97.1484934648714m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1064)
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1068),
                            Name = "Mugs_Product_48",
                            Price = 9.92279861743112m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1069)
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1072),
                            Name = "Mugs_Product_49",
                            Price = 46.2172959083072m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1074)
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1077),
                            Name = "Mugs_Product_50",
                            Price = 13.1942286737632m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1078)
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1082),
                            Name = "Mugs_Product_51",
                            Price = 95.80965211291m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1084)
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1088),
                            Name = "Mugs_Product_52",
                            Price = 37.356956350505m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1090)
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1095),
                            Name = "Filters_Product_53",
                            Price = 20.867670089016m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1097)
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1101),
                            Name = "Filters_Product_54",
                            Price = 1.76144535880296m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1103)
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1107),
                            Name = "Filters_Product_55",
                            Price = 74.2241742278283m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1109)
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1112),
                            Name = "Filters_Product_56",
                            Price = 0.832253239474223m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1114)
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1118),
                            Name = "Filters_Product_57",
                            Price = 86.4766102048189m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1120)
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1124),
                            Name = "Filters_Product_58",
                            Price = 12.4801751105648m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1126)
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1130),
                            Name = "Filters_Product_59",
                            Price = 12.1089477301959m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1132)
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1158),
                            Name = "Filters_Product_60",
                            Price = 96.407711891893m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1160)
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1164),
                            Name = "Filters_Product_61",
                            Price = 53.9614055583014m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1166)
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1169),
                            Name = "Filters_Product_62",
                            Price = 26.6239686847944m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1170)
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 14,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1174),
                            Name = "Pastries_Product_63",
                            Price = 84.2221969718261m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1175)
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 14,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1179),
                            Name = "Pastries_Product_64",
                            Price = 77.4154511428757m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1180)
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 14,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1183),
                            Name = "Pastries_Product_65",
                            Price = 82.4542187359255m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1185)
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 14,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1189),
                            Name = "Pastries_Product_66",
                            Price = 61.4370134209941m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1191)
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 14,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1194),
                            Name = "Pastries_Product_67",
                            Price = 1.49691187136946m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1196)
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 14,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1199),
                            Name = "Pastries_Product_68",
                            Price = 30.8376853854718m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1200)
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 15,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1204),
                            Name = "Snacks_Product_69",
                            Price = 96.206813742679m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1205)
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 15,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1209),
                            Name = "Snacks_Product_70",
                            Price = 26.2249517605355m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1210)
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 15,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1213),
                            Name = "Snacks_Product_71",
                            Price = 53.7697321136391m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1215)
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 15,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1218),
                            Name = "Snacks_Product_72",
                            Price = 64.8840652622763m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1219)
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 15,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1223),
                            Name = "Snacks_Product_73",
                            Price = 38.3092621340722m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1224)
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 16,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1228),
                            Name = "Syrups_Product_74",
                            Price = 89.6013793822942m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1230)
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 16,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1234),
                            Name = "Syrups_Product_75",
                            Price = 62.213402406816m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1236)
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 16,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1240),
                            Name = "Syrups_Product_76",
                            Price = 26.7024711378894m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1242)
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 16,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1246),
                            Name = "Syrups_Product_77",
                            Price = 2.58616055041865m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1248)
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 16,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1252),
                            Name = "Syrups_Product_78",
                            Price = 33.2890924691161m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1254)
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 17,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1258),
                            Name = "MilkAlternatives_Product_79",
                            Price = 43.412004692526m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1260)
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 17,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1264),
                            Name = "MilkAlternatives_Product_80",
                            Price = 43.5707966102519m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1266)
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 17,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1270),
                            Name = "MilkAlternatives_Product_81",
                            Price = 71.2231927471381m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1272)
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 17,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1276),
                            Name = "MilkAlternatives_Product_82",
                            Price = 85.738483465914m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1278)
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 17,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1282),
                            Name = "MilkAlternatives_Product_83",
                            Price = 42.6139904560449m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1284)
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 17,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1288),
                            Name = "MilkAlternatives_Product_84",
                            Price = 7.43867489148471m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1290)
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 17,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1294),
                            Name = "MilkAlternatives_Product_85",
                            Price = 90.4962373368914m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1296)
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 17,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1299),
                            Name = "MilkAlternatives_Product_86",
                            Price = 0.195085747373325m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1301)
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 18,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1306),
                            Name = "Merchandise_Product_87",
                            Price = 28.7324651182295m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1307)
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 18,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1311),
                            Name = "Merchandise_Product_88",
                            Price = 9.28959084902047m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1313)
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 18,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1316),
                            Name = "Merchandise_Product_89",
                            Price = 79.5036800931876m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1318)
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 18,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1321),
                            Name = "Merchandise_Product_90",
                            Price = 10.8738081387147m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1322)
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 18,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1325),
                            Name = "Merchandise_Product_91",
                            Price = 30.0191063787569m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1327)
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 19,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1330),
                            Name = "Subscriptions_Product_92",
                            Price = 81.7429766490015m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1332)
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 19,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1335),
                            Name = "Subscriptions_Product_93",
                            Price = 83.3831724259632m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1336)
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 19,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1340),
                            Name = "Subscriptions_Product_94",
                            Price = 99.4189285471502m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1341)
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 19,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1344),
                            Name = "Subscriptions_Product_95",
                            Price = 38.0154198548681m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1346)
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 19,
                            CreatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1349),
                            Name = "Subscriptions_Product_96",
                            Price = 6.44054916033342m,
                            UpdatedAt = new DateTime(2024, 7, 4, 11, 57, 32, 201, DateTimeKind.Local).AddTicks(1351)
                        });
                });

            modelBuilder.Entity("CoffeeShop.Products.Api.Models.Category", b =>
                {
                    b.HasOne("CoffeeShop.Products.Api.Models.Category", "ParentCategory")
                        .WithMany("Subcategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("CoffeeShop.Products.Api.Models.Product", b =>
                {
                    b.HasOne("CoffeeShop.Products.Api.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CoffeeShop.Products.Api.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Subcategories");
                });
#pragma warning restore 612, 618
        }
    }
}
