version: '3.8'

services:
  coffeeshop.products.api:
    build:
      context: .
      dockerfile: CoffeeShop.Products.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ProductsConnection=Server=sqlserver;Database=CoffeeShop_Products;User=sa;Password=MyPass123;TrustServerCertificate=True;
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "MyPass123"
    ports:
      - "1433:1433"
